// lib/fee-outlook.ts — v27aw
//
// Cockpit Fee Outlook computation.
//
// Per portfolio, returns:
//   - "as of today" metrics (current_nav, target_nav, excess_ngn/pct) sourced
//     from the engine's pending fee_periods row (ground truth).
//   - crystallised_ytd_fee: sum of pending fee_periods.fee_earned (ground truth
//     from the engine's most recent recompute).
//   - projected_year_end_fee: walker output assuming today's NAV is held flat
//     through fee_year_end. Implements the CIO's "freeze NAV forward" projection
//     philosophy — never project gains we haven't already delivered.
//
// Math delegated to lib/fee-math.ts walkPeriods (Mode 2: forward projection
// via projectNavForward with assumedAnnualReturn=0). Fixes cockpit divergences:
//
//   #133 — Unanchored fee-bearing portfolios now short-circuit to FeeStatus
//          'unanchored' instead of falling through to performance math against
//          starting_nav.
//   #134 — Year-start basis driver is now fee_relationship_start_date (the
//          fee accrual anchor) not start_date (mandate inception).
//   #135 — Cashflow window for the projection is automatically anchor-aware
//          because periods generated by walkPeriods derive from the anchor.
//
// Backwards compat: projected_annual_fee is preserved as an alias for
// projected_year_end_fee so app/api/cockpit/summary/route.ts (which sums
// projected_annual_fee for the firmwide KPI) keeps working without
// modification. Phase out in a future ship if desired.

import {
  walkPeriods,
  projectNavForward,
  num,
  numOrNull,
  type FeeWalkConfig,
  type NavLogRow,
  type TransactionRow,
  type PreservedPeriodRow,
} from './fee-math'
import { type FeeModel } from './fee-calc'

// Local minimal portfolio shape — engine doesn't depend on lib/portfolio.ts types
export interface FeeOutlookPortfolio {
  id: string
  name: string
  starting_nav: number
  start_date: string
  client?: { name: string; code: string; type?: string }
  fee_model?: FeeModel | null
  fixed_annual_fee_ngn?: number | null
  target_return?: number | null
  performance_fee_split?: number | null
  // v27aw: anchor + year-end MM-DD. Required for hold-flat projection.
  fee_year_end_md?: string | null
  fee_relationship_start_date?: string | null
}

// Engine ground-truth row: latest pending fee_periods row for this portfolio.
// Provides "as of today" excess and target metrics without re-deriving them
// in the cockpit layer.
export interface TodaysPendingRow {
  fee_earned:              number
  excess_above_threshold:  number | null
  closing_nav:             number | null
  opening_nav:             number | null
}

// ─── Status enum ──────────────────────────────────────────────
// v27aw: 'unanchored' added for performance/combined portfolios with NULL
// fee_relationship_start_date.
export type FeeStatus =
  | 'beating' | 'on_track' | 'at_risk' | 'below'
  | 'no_basis' | 'fixed_annual' | 'no_fee' | 'unanchored'

export interface FeeOutlook {
  portfolio_id:   string
  portfolio_name: string
  client_name:    string
  client_code:    string
  is_internal:    boolean

  // v27ao
  is_fixed_annual?:      boolean
  fixed_annual_fee_ngn?: number | null
  pro_rata_ytd_fee?:     number

  // v27aw
  is_unanchored?:        boolean

  year_start_basis:           'jan_1' | 'mandate_start'
  effective_year_start_date:  string
  days_elapsed:               number
  days_remaining:             number
  days_in_year:               number

  current_nav:  number
  target_nav:   number
  excess_ngn:   number
  excess_pct:   number

  // v27aw NEW: separate ground truth from forward bet
  crystallised_ytd_fee:    number  // sum of pending fee_periods.fee_earned
  projected_year_end_fee:  number  // walker output assuming today's NAV held flat

  // BACKWARDS-COMPAT alias for v27aw transition. Equals projected_year_end_fee.
  // Allows app/api/cockpit/summary/route.ts's `fo.projected_annual_fee` reads
  // to keep working without modification.
  projected_annual_fee: number

  // Legacy field, kept defined for any older consumer. = current excess
  // linearly extrapolated to year-end. Not the basis for projected_year_end_fee.
  projected_year_end_excess_ngn: number

  status: FeeStatus
}

// ─── DMA defaults ─────────────────────────────────────────────
// Backstops for performance-mode portfolios when target_return or
// performance_fee_split is null in the database.
const ANNUAL_TARGET_DEFAULT = 0.15
// (FIRM_SHARE_DEFAULT no longer needed — walker reads split per-portfolio)

// ─── Year boundary helpers ─────────────────────────────────────
function yearStartOf(date: Date): Date {
  return new Date(date.getFullYear(), 0, 1)
}
function yearEndOf(date: Date): Date {
  return new Date(date.getFullYear() + 1, 0, 1)
}
function daysBetween(from: Date, to: Date): number {
  return Math.max(0, Math.round((to.getTime() - from.getTime()) / 86_400_000))
}
function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10)
}

// Compute the fee-year-end Date from asOf and fee_year_end_md ('MM-DD').
// Most live portfolios use '12-31' → year-end is Dec 31 of asOf's year.
// If asOf is past this year's MM-DD (e.g. fee year already crystallised),
// uses next year's. Defensive.
function computeFeeYearEnd(asOf: Date, feeYearEndMD: string): Date {
  const parts = feeYearEndMD.split('-').map(Number)
  const mm = parts[0] ?? 12
  const dd = parts[1] ?? 31
  const thisYear = new Date(asOf.getFullYear(), mm - 1, dd)
  if (asOf > thisYear) {
    return new Date(asOf.getFullYear() + 1, mm - 1, dd)
  }
  return thisYear
}

// ─── Status classification ────────────────────────────────────
function classifyStatus(excess: number, currentNAV: number, projected: number): FeeStatus {
  if (currentNAV <= 0) return 'no_basis'
  const excessRatio = excess / currentNAV
  if (excess >= 0 && projected > 0) return 'beating'
  if (excessRatio >= -0.02) return 'on_track'
  if (excessRatio >= -0.05) return 'at_risk'
  return 'below'
}

// ═══════════════════════════════════════════════════════════════
// MAIN ENTRY POINT — v27aw
// ═══════════════════════════════════════════════════════════════

export interface FeeOutlookInput {
  portfolio: FeeOutlookPortfolio
  totalNAV: number
  // v27aw: walker inputs (replaces v27ao's navAtYearStart + yearlyCashflows)
  navRows: NavLogRow[]
  txRows: TransactionRow[]
  preservedRows: PreservedPeriodRow[]
  crystallisedYtdFee: number
  todaysPending: TodaysPendingRow | null
  asOf?: Date
}

export function computeFeeOutlook(input: FeeOutlookInput): FeeOutlook {
  const {
    portfolio, totalNAV, navRows, txRows, preservedRows,
    crystallisedYtdFee, todaysPending, asOf = new Date(),
  } = input

  const isInternal = portfolio.fee_model === 'none' || portfolio.client?.type === 'internal'
  const yStart = yearStartOf(asOf)
  const yEnd = yearEndOf(asOf)
  const daysInYear = daysBetween(yStart, yEnd)

  // v27aw fix #134: basis driver is now fee_relationship_start_date.
  const anchor = portfolio.fee_relationship_start_date
    ? new Date(portfolio.fee_relationship_start_date)
    : null
  const startedThisYear = anchor !== null && anchor >= yStart
  const effectiveStart = anchor && startedThisYear ? anchor : yStart
  const basis: 'jan_1' | 'mandate_start' = startedThisYear ? 'mandate_start' : 'jan_1'

  const daysElapsed = Math.max(1, daysBetween(effectiveStart, asOf))
  const daysRemaining = Math.max(0, daysBetween(asOf, yEnd))

  // ─── Branch 1: no_fee (internal or fee_model='none') ─────────
  if (isInternal) {
    return {
      portfolio_id:   portfolio.id,
      portfolio_name: portfolio.name,
      client_name:    portfolio.client?.name ?? '—',
      client_code:    portfolio.client?.code ?? '—',
      is_internal:    true,

      year_start_basis:           basis,
      effective_year_start_date:  isoDate(effectiveStart),
      days_elapsed:               daysElapsed,
      days_remaining:             daysRemaining,
      days_in_year:               daysInYear,

      current_nav: totalNAV,
      target_nav:  0,
      excess_ngn:  0,
      excess_pct:  0,

      crystallised_ytd_fee:           0,
      projected_year_end_fee:         0,
      projected_annual_fee:           0,
      projected_year_end_excess_ngn:  0,
      status: 'no_fee',
    }
  }

  // ─── Branch 2: fixed_annual ──────────────────────────────────
  if (portfolio.fee_model === 'fixed_annual') {
    const annualFee = num(portfolio.fixed_annual_fee_ngn, 0)
    const ytdProRata = annualFee * (daysElapsed / Math.max(1, daysInYear))
    return {
      portfolio_id:   portfolio.id,
      portfolio_name: portfolio.name,
      client_name:    portfolio.client?.name ?? '—',
      client_code:    portfolio.client?.code ?? '—',
      is_internal:    false,
      is_fixed_annual: true,
      fixed_annual_fee_ngn: annualFee,
      pro_rata_ytd_fee: ytdProRata,

      year_start_basis:           basis,
      effective_year_start_date:  isoDate(effectiveStart),
      days_elapsed:               daysElapsed,
      days_remaining:             daysRemaining,
      days_in_year:               daysInYear,

      current_nav: totalNAV,
      target_nav:  0,
      excess_ngn:  0,
      excess_pct:  0,

      // For fixed_annual, crystallised = engine row's pro-rated value if present;
      // fall back to time-pro-rata math when no pending row exists yet.
      crystallised_ytd_fee:           crystallisedYtdFee > 0 ? crystallisedYtdFee : ytdProRata,
      projected_year_end_fee:         annualFee,
      projected_annual_fee:           annualFee,  // backwards-compat alias
      projected_year_end_excess_ngn:  0,
      status: 'fixed_annual',
    }
  }

  // ─── Branch 3: unanchored fee-bearing portfolio (v27aw fix #133) ─
  // Performance/combined portfolios without fee_relationship_start_date set
  // never enter the engine's recompute path (engine returns skip=true). Cockpit
  // similarly short-circuits — show "Unanchored" rather than projecting fees
  // against unreliable basis (the v27ao bug that surfaced as CMFB-A BEATING
  // ₦10.50M projected despite null anchor).
  if (!portfolio.fee_relationship_start_date) {
    return {
      portfolio_id:   portfolio.id,
      portfolio_name: portfolio.name,
      client_name:    portfolio.client?.name ?? '—',
      client_code:    portfolio.client?.code ?? '—',
      is_internal:    false,
      is_unanchored:  true,

      year_start_basis:           'jan_1',
      effective_year_start_date:  isoDate(yStart),
      days_elapsed:               daysElapsed,
      days_remaining:             daysRemaining,
      days_in_year:               daysInYear,

      current_nav: totalNAV,
      target_nav:  0,
      excess_ngn:  0,
      excess_pct:  0,

      crystallised_ytd_fee:           0,
      projected_year_end_fee:         0,
      projected_annual_fee:           0,
      projected_year_end_excess_ngn:  0,
      status: 'unanchored',
    }
  }

  // ─── Branch 4: performance modes — delegate to walker ────────
  // walkPeriods handles performance_excess, performance_hwm, performance_combined
  // uniformly. Hold-flat projection: synthesise NAV row at fee_year_end equal
  // to today's totalNAV (CIO philosophy — never project gains we haven't earned).
  const config: FeeWalkConfig = {
    fee_model: (portfolio.fee_model ?? 'performance_excess') as FeeModel,
    target_return: num(portfolio.target_return, ANNUAL_TARGET_DEFAULT),
    performance_fee_split: numOrNull(portfolio.performance_fee_split),
    fixed_annual_fee_ngn: numOrNull(portfolio.fixed_annual_fee_ngn),
    fee_year_end_md: portfolio.fee_year_end_md ?? '12-31',
    fee_relationship_start_date: portfolio.fee_relationship_start_date,
  }

  const feeYearEnd = computeFeeYearEnd(asOf, config.fee_year_end_md)

  // Ensure today's actual NAV is the seed for projection (nav_log can be a day
  // stale; totalNAV is live). Insert today's totalNAV into navRows.
  const navRowsWithToday: NavLogRow[] = [
    ...navRows,
    { nav_date: isoDate(asOf), nav_value: totalNAV },
  ].sort((a, b) =>
    a.nav_date < b.nav_date ? -1 : a.nav_date > b.nav_date ? 1 : 0
  )

  // Hold-flat: feed walker NAV rows that hold at totalNAV through fee_year_end.
  const projectedNavRows = projectNavForward({
    navRows: navRowsWithToday,
    asOf,
    throughDate: feeYearEnd,
    assumedAnnualReturn: 0,
  })

  // Run walker with year-end as asOf — produces the fee that would crystallise
  // at fee_year_end if NAV held at totalNAV.
  const walkResult = walkPeriods({
    config,
    navRows: projectedNavRows,
    txRows,
    preservedRows,
    asOf: feeYearEnd,
  })

  let projectedYearEndFee = 0
  if (walkResult.ok) {
    for (const cp of walkResult.computedPeriods) {
      projectedYearEndFee += cp.fee_earned
    }
  }

  // "As of today" metrics: prefer engine ground truth (latest pending row).
  // Falls back to first-principles approximation if engine has no row yet
  // (i.e. recompute hasn't run since anchoring — should be rare in practice).
  let targetNav = 0
  let excessNgn = 0
  let excessPct = 0
  if (todaysPending) {
    const closingNav = num(todaysPending.closing_nav, totalNAV)
    const excess = num(todaysPending.excess_above_threshold, 0)
    targetNav = closingNav - excess
    excessNgn = excess
    excessPct = targetNav > 0 ? excessNgn / targetNav : 0
  } else {
    targetNav = totalNAV
    excessNgn = 0
    excessPct = 0
  }

  // Legacy field — current excess linearly extrapolated to year-end. Kept
  // defined for any older consumer; no longer drives the projected fee.
  const extrapolationFactor = daysInYear / Math.max(1, daysElapsed)
  const projectedYearEndExcess = excessNgn * extrapolationFactor

  const status = classifyStatus(excessNgn, totalNAV, projectedYearEndFee)

  return {
    portfolio_id:   portfolio.id,
    portfolio_name: portfolio.name,
    client_name:    portfolio.client?.name ?? '—',
    client_code:    portfolio.client?.code ?? '—',
    is_internal:    false,

    year_start_basis:           basis,
    effective_year_start_date:  isoDate(effectiveStart),
    days_elapsed:               daysElapsed,
    days_remaining:             daysRemaining,
    days_in_year:               daysInYear,

    current_nav: totalNAV,
    target_nav:  targetNav,
    excess_ngn:  excessNgn,
    excess_pct:  excessPct,

    crystallised_ytd_fee:           crystallisedYtdFee,
    projected_year_end_fee:         projectedYearEndFee,
    projected_annual_fee:           projectedYearEndFee,  // backwards-compat alias
    projected_year_end_excess_ngn:  projectedYearEndExcess,
    status,
  }
}
