'use client'
import { useEffect, useState, useCallback } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import * as XLSX from 'xlsx'
import {
  RefreshCw, FileText, Download, AlertTriangle, Info, FileSpreadsheet, Sparkles,
} from 'lucide-react'
import dynamic from 'next/dynamic'
import { supabase } from '@/lib/supabase'
import {
  computeNAV, computeSleeveData, estimatedIncomePA,
  fmt, type Portfolio, type Holding, type SleeveTarget,
} from '@/lib/portfolio'
import { fmtSignedNGN } from '@/lib/fee-calc'  // v27l: fee panel
import { computeMandateHealth, healthToLegacyAlerts } from '@/lib/mandate-health'

// v20c: Sidebar is rendered by app/portfolio/[id]/layout.tsx.
// v20: Hybrid Portfolio Overview — single page, no internal tabs.
// v21g: Performance panel surfaces IRR + period returns + benchmarks.
// v21h: Sector Concentration panel surfaces NAV-weighted sector breakdown.
// v21j: Excel export via SheetJS.
// v21n: KPI strip sub-labels fixed. "Current NAV" sub and "Unrealised P&L"
//   sub now show ITD IRR p.a. (from the analytics route) instead of raw HPR.
// v21y: "Run scenario" button in the header action row opens a modal for
//   ephemeral scenario analysis. Results can be copied or saved to the
//   reports table (report_type = 'scenario' added via companion SQL).
// v27b: Compliance alerts now generated by the mandate-health engine via
//   the legacy adapter — same { level, message } shape, but driven by the
//   11-check surveillance system that powers the cockpit Mandate Health Grid.
//   This brings the per-portfolio banner into alignment with the firm-wide
//   grid. Three new fetches added to load(): nav history (drawdown), recent
//   txn count (activity), and days since last report (cadence). ytdReturn is
//   passed as null because analytics loads asynchronously; the benchmark
//   check correctly returns 'na' which the adapter suppresses.
//
// Pitfall #7: the "Download report" button MUST remain in the header
// and MUST call /api/export?portfolioId=... The apply-update.sh greps
// for both "Download report" and "/api/export".

const AllocationDonut = dynamic(() => import('@/components/portfolio/AllocationDonut'), { ssr: false })
const SectorDonut     = dynamic(() => import('@/components/portfolio/SectorDonut'),     { ssr: false })
const ScenarioModal   = dynamic(() => import('@/components/portfolio/ScenarioModal'),   { ssr: false })

const SLEEVE_FILL: Record<string, string> = {
  liq: 'var(--sidebar-bg)',
  eq:  'linear-gradient(90deg, var(--gold), var(--gold-bright))',
  fi:  'var(--pos)',
}

const PERIOD_TABS: { key: string; label: string }[] = [
  // v27j: period set — fee-calculation-aligned tabs
  { key: 'YTD', label: 'YTD' },
  { key: 'LY',  label: 'LY'  },
  { key: 'L3Y', label: 'L3Y' },
  { key: 'L5Y', label: 'L5Y' },
  { key: 'ITD', label: 'ITD' },
]

function fmtPctSigned(v: number | null | undefined, digits = 2): string {
  if (v === null || v === undefined || isNaN(v)) return '—'
  const s = (v * 100).toFixed(digits)
  return (v >= 0 ? '+' : '') + s + '%'
}

function fmtIRR(v: number | null | undefined, digits = 2): { value: string; hasValue: boolean } {
  if (v === null || v === undefined || isNaN(v)) return { value: '—', hasValue: false }
  const s = (v * 100).toFixed(digits)
  return { value: (v >= 0 ? '+' : '') + s + '%', hasValue: true }
}

function buildSectorSlices(holdings: any[]): { slices: any[]; totalEquityNAV: number } {
  const equities = holdings.filter(h => h.instrument?.type === 'Stock')
  const totalEquityNAV = equities.reduce((s, h) => s + (h.quantity * (h.latest_price ?? h.avg_cost ?? 0)), 0)
  if (totalEquityNAV <= 0) return { slices: [], totalEquityNAV: 0 }
  const bySector = new Map<string, { value: number; count: number }>()
  for (const h of equities) {
    const sector = h.instrument?.sector || 'Unclassified'
    const value  = h.quantity * (h.latest_price ?? h.avg_cost ?? 0)
    if (value <= 0) continue
    const prev = bySector.get(sector) ?? { value: 0, count: 0 }
    bySector.set(sector, { value: prev.value + value, count: prev.count + 1 })
  }
  const slices = Array.from(bySector.entries())
    .map(([sector, { value, count }]) => ({
      sector, value, pct: value / totalEquityNAV, count,
    }))
    .sort((a, b) => b.value - a.value)
  return { slices, totalEquityNAV }
}

export default function PortfolioOverviewPage() {
  const params      = useParams()
  const portfolioId = params.id as string

  const [portfolio, setPortfolio]       = useState<Portfolio | null>(null)
  const [holdings, setHoldings]         = useState<Holding[]>([])
  const [sleeveDefs, setSleeveDefs]     = useState<SleeveTarget[]>([])
  const [loading, setLoading]           = useState(true)
  const [refreshing, setRefreshing]     = useState(false)
  const [fxRate, setFxRate]             = useState<number>(1665)
  const [dividends, setDividends]       = useState<any>(null)
  const [divLoading, setDivLoading]     = useState(false)
  const [divRefreshing, setDivRefreshing] = useState(false)
  const [divRefreshMsg, setDivRefreshMsg] = useState('')
  const [divFreshness, setDivFreshness] = useState<Date | null>(null)

  const [analyticsPeriod, setAnalyticsPeriod] = useState<string>('YTD')  // v27j: default tab
  const [showAudit, setShowAudit] = useState<boolean>(false)  // v27l
  const [analytics, setAnalytics]             = useState<any>(null)
  const [analyticsLoading, setAnalyticsLoading] = useState(false)

  // v21y: Scenario modal state
  const [scenarioOpen, setScenarioOpen] = useState(false)

  // v27b: mandate-health engine inputs
  const [navHistory, setNavHistory] = useState<{ nav_date: string; nav_value: number }[]>([])
  const [recentTxnCount90d, setRecentTxnCount90d] = useState<number>(0)
  const [daysSinceLastReport, setDaysSinceLastReport] = useState<number | null>(null)

  const load = useCallback(async () => {
    // v27b — three additional reads added for the mandate-health engine:
    //   nav_log         → drawdown check
    //   transactions    → recent activity check (90d, ex-FEE)
    //   reports         → report-current check (days since last report)
    const cutoff90 = new Date()
    cutoff90.setDate(cutoff90.getDate() - 90)
    const cutoff90Iso = cutoff90.toISOString().slice(0, 10)

    const [portRes, holdRes, sleeveRes, navLogRes, txnRes, reportRes] = await Promise.all([
      supabase.from('portfolios').select('*, client:clients(name,code,type)').eq('id', portfolioId).single(),
      supabase.from('holdings').select('*, instrument:instruments(*)').eq('portfolio_id', portfolioId),
      supabase.from('sleeve_targets').select('*').eq('portfolio_id', portfolioId).order('sort_order'),
      supabase.from('nav_log')
        .select('nav_date, nav_value')
        .eq('portfolio_id', portfolioId)
        .order('nav_date', { ascending: true })
        .limit(50000),
      supabase.from('transactions')
        .select('id', { count: 'exact', head: true })
        .eq('portfolio_id', portfolioId)
        .gte('trade_date', cutoff90Iso)
        .neq('action', 'FEE'),
      supabase.from('reports')
        .select('report_date')
        .eq('portfolio_id', portfolioId)
        .order('report_date', { ascending: false })
        .limit(1)
        .maybeSingle(),
    ])
    if (portRes.data)  setPortfolio(portRes.data)
    if (sleeveRes.data) setSleeveDefs(sleeveRes.data)

    // navHistory hydration (numeric coercion at boundary — pitfall #72)
    if (navLogRes.data) {
      const hydrated = (navLogRes.data as any[])
        .map(r => ({ nav_date: r.nav_date as string, nav_value: Number(r.nav_value) }))
        .filter(r => isFinite(r.nav_value))
      setNavHistory(hydrated)
    } else {
      setNavHistory([])
    }

    // 90-day non-FEE transaction count
    setRecentTxnCount90d(txnRes.count ?? 0)

    // Days since most recent report (any type)
    if (reportRes.data?.report_date) {
      const lastDate = new Date(reportRes.data.report_date)
      const days = Math.round((Date.now() - lastDate.getTime()) / 86_400_000)
      setDaysSinceLastReport(days)
    } else {
      setDaysSinceLastReport(null)
    }

    if (holdRes.data) {
      const { data: prices } = await supabase
        .from('market_prices')
        .select('instrument_id, price, day_change')
        .in('instrument_id', holdRes.data.map((h: any) => h.instrument_id))
        .order('price_date', { ascending: false })
      const priceMap: Record<string, { price: number; day_change: number }> = {}
      prices?.forEach((p: any) => {
        if (!priceMap[p.instrument_id]) {
          priceMap[p.instrument_id] = { price: p.price, day_change: p.day_change ?? 0 }
        }
      })
      setHoldings(holdRes.data.map((h: any) => ({
        ...h,
        latest_price: priceMap[h.instrument_id]?.price ?? h.avg_cost,
        day_change:   priceMap[h.instrument_id]?.day_change ?? 0,
      })))
    }
    setLoading(false)
  }, [portfolioId])

  useEffect(() => { load() }, [load])

  useEffect(() => {
    fetch('https://api.exchangerate-api.com/v4/latest/USD')
      .then(r => r.json())
      .then(d => { if (d.rates?.NGN) setFxRate(d.rates.NGN) })
      .catch(() => {})
  }, [])

  useEffect(() => {
    if (!portfolioId) return
    setDivLoading(true)
    fetch(`/api/dividends?portfolioId=${portfolioId}`)
      .then(r => r.json())
      .then(d => { setDividends(d); setDivLoading(false) })
      .catch(() => setDivLoading(false))
  }, [portfolioId, holdings.length])

  useEffect(() => {
    supabase
      .from('instruments')
      .select('div_last_refreshed_at')
      .eq('type', 'Stock').eq('approved', true)
      .not('div_last_refreshed_at', 'is', null)
      .order('div_last_refreshed_at', { ascending: false })
      .limit(1).maybeSingle()
      .then(({ data }) => {
        if (data?.div_last_refreshed_at) setDivFreshness(new Date(data.div_last_refreshed_at))
      })
  }, [])

  useEffect(() => {
    if (!portfolioId || loading) return
    setAnalyticsLoading(true)
    fetch(`/api/analytics?portfolioId=${portfolioId}&period=${analyticsPeriod}`)
      .then(r => r.json())
      .then(d => { setAnalytics(d); setAnalyticsLoading(false) })
      .catch(() => { setAnalyticsLoading(false) })
  }, [portfolioId, analyticsPeriod, loading])

  async function refreshDividends() {
    setDivRefreshing(true); setDivRefreshMsg('')
    try {
      const res = await fetch('/api/dividends/refresh', { method: 'POST' })
      const d   = await res.json()
      setDivRefreshMsg(d.ok ? `✓ ${d.message ?? 'refreshed'}` : 'Refresh failed')
      const r2 = await fetch(`/api/dividends?portfolioId=${portfolioId}`)
      setDividends(await r2.json())
      const { data: f } = await supabase
        .from('instruments').select('div_last_refreshed_at')
        .eq('type', 'Stock').eq('approved', true)
        .not('div_last_refreshed_at', 'is', null)
        .order('div_last_refreshed_at', { ascending: false })
        .limit(1).maybeSingle()
      if (f?.div_last_refreshed_at) setDivFreshness(new Date(f.div_last_refreshed_at))
      setTimeout(() => setDivRefreshMsg(''), 6000)
    } catch { setDivRefreshMsg('Refresh failed') }
    setDivRefreshing(false)
  }

  async function refreshPrices() {
    setRefreshing(true)
    try {
      const res = await fetch('/api/prices', { method: 'POST', body: JSON.stringify({ portfolioId }) })
      if (res.ok) await load()
    } finally { setRefreshing(false) }
  }

  if (loading || !portfolio) {
    return (
      <div className="hybrid-page" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-3)', fontSize: 14, minHeight: '100vh' }}>
        Loading portfolio…
      </div>
    )
  }

  const tot            = computeNAV(holdings)
  const sv             = computeSleeveData(holdings, sleeveDefs, tot)
  const hasStartingNav = portfolio.starting_nav > 0
  const pl             = tot - portfolio.starting_nav
  const ret            = hasStartingNav ? pl / portfolio.starting_nav : 0   // raw HPR — only used as fallback
  const incPA          = dividends?.totalEstimatedIncome ?? estimatedIncomePA(holdings)
  const { slices: sectorSlices, totalEquityNAV } = buildSectorSlices(holdings)

  // v27b — alerts now produced by the mandate-health engine (11-check surveillance)
  // via the legacy adapter. ytdReturn is null because analytics loads asynchronously;
  // the benchmark check returns 'na' which the adapter suppresses (na/green → no alert).
  const alerts = healthToLegacyAlerts(computeMandateHealth({
    portfolio: portfolio as any,
    holdings: holdings as any,
    sleeveDefs: sleeveDefs as any,
    totalNAV: tot,
    navHistory,
    recentTxnCount90d,
    daysSinceLastReport,
    ytdReturn: null,
  }))

  // v21n: derive ITD IRR from analytics.allPeriods (loaded asynchronously).
  const itdAnalytics   = analytics?.allPeriods?.find((p: any) => p.period === 'ITD')
  const itdIRR: number | null = itdAnalytics?.irr ?? null
  const itdIRRDisplay  = fmtIRR(itdIRR)

  const divStaleInfo = (() => {
    if (!divFreshness) return { cls: 'none', text: 'Dividend data: never refreshed' }
    const days    = Math.floor((Date.now() - divFreshness.getTime()) / 86_400_000)
    const fmtDate = divFreshness.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: '2-digit' })
    if (days <= 14) return { cls: 'fresh', text: `Fresh · refreshed ${fmtDate}` }
    return { cls: 'stale', text: `Data ${days}d old · refreshed ${fmtDate}` }
  })()

  const metrics          = analytics?.period
  const irrDisplay       = fmtIRR(metrics?.irr)
  const periodLabel      = metrics?.periodLabel ?? PERIOD_TABS.find(t => t.key === analyticsPeriod)?.label ?? analyticsPeriod
  const daysHeld         = metrics?.daysHeld ?? null
  const hasEnoughDataForIRR = metrics?.startNAV !== null && metrics?.startNAV !== undefined && metrics.startNAV > 0 && (daysHeld ?? 0) > 0

  // v21j: Excel export — 4-sheet workbook
  function downloadExcel() {
    if (!portfolio) return
    const wb         = XLSX.utils.book_new()
    const today      = new Date().toLocaleDateString('en-GB')
    const clientName = (portfolio as any).client?.name ?? ''
    const portfolioName = portfolio.name

    // Sheet 1: Summary
    const summaryRows: any[][] = [
      ['PORTFOLIO OVERVIEW', ''],
      ['Client', clientName],
      ['Portfolio', portfolioName],
      ['Export date', today],
      [''],
      ['NAV SUMMARY', ''],
      ['Current NAV (₦)', tot],
      ['Starting NAV (₦)', portfolio.starting_nav ?? 0],
      ['Unrealised P&L (₦)', tot - (portfolio.starting_nav ?? 0)],
      ['ITD IRR p.a.', itdIRR !== null ? itdIRR : ''],
      ['Raw HPR (unadjusted)', hasStartingNav ? ret : ''],
      ['Est. income p.a. (₦)', incPA ?? 0],
      ['Income target', portfolio.income_target ?? ''],
      ['Start date', portfolio.start_date ?? ''],
      [''],
      [`PERFORMANCE (${analyticsPeriod})`, ''],
      ['IRR p.a.', metrics?.irr ?? ''],
      ['Period return', metrics?.simplePeriodReturn ?? ''],
      ['Absolute P&L (₦)', metrics?.absoluteReturn ?? ''],
      ['TWR (ann.)', metrics?.twrAnnualised ?? metrics?.twr ?? ''],
      ['Days held', metrics?.daysHeld ?? ''],
      ['Period start', metrics?.startDate ?? ''],
      ['Period end', metrics?.endDate ?? ''],
      ['Net cash flows (₦)', metrics?.netCashFlows ?? ''],
    ]
    if (metrics?.benchmarks?.length > 0) {
      summaryRows.push([''])
      summaryRows.push(['BENCHMARKS', 'Annual rate'])
      metrics.benchmarks.forEach((b: any) => summaryRows.push([b.shortName, b.annualRate ?? '']))
    }
    const summaryWs = XLSX.utils.aoa_to_sheet(summaryRows)
    summaryWs['!cols'] = [{ wch: 26 }, { wch: 20 }]
    XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary')

    // Sheet 2: Allocation
    const allocHeaders = [
      'Sleeve', 'Target %', 'Actual %',
      'Target Value (₦)', 'Actual Value (₦)', 'Deviation (₦)', 'Status', 'Suggested',
    ]
    const allocRows = (sv as any[]).map((s: any) => {
      const d      = s.diff ?? 0
      const action = d > 50000 ? 'Buy' : d < -50000 ? 'Sell' : 'Hold'
      return [
        s.name,
        Number(((s.target_pct ?? 0) * 100).toFixed(2)),
        Number(((s.act ?? 0) * 100).toFixed(2)),
        tot * (s.target_pct ?? 0),
        s.val ?? 0,
        d,
        s.status,
        action,
      ]
    })
    const allocWs = XLSX.utils.aoa_to_sheet([allocHeaders, ...allocRows])
    allocWs['!cols'] = [
      { wch: 22 }, { wch: 10 }, { wch: 10 },
      { wch: 18 }, { wch: 18 }, { wch: 18 }, { wch: 10 }, { wch: 10 },
    ]
    XLSX.utils.book_append_sheet(wb, allocWs, 'Allocation')

    // Sheet 3: Holdings
    const holdHeaders = [
      'Instrument', 'Ticker', 'Type', 'Sector', 'Sleeve',
      'Quantity', 'Avg Cost (₦)', 'Current Price (₦)',
      'Market Value (₦)', 'Unrealised P&L (₦)', 'Weight %',
    ]
    const holdRows = (holdings as any[]).map(h => {
      const p   = h.latest_price ?? h.avg_cost ?? 1
      const v   = Number(h.quantity) * p
      const pnl = Number(h.quantity) * (p - Number(h.avg_cost))
      const wt  = tot > 0 ? Number((v / tot * 100).toFixed(2)) : 0
      return [
        h.instrument?.name ?? h.instrument_id,
        h.instrument_id,
        h.instrument?.type ?? '',
        h.instrument?.sector ?? '',
        h.sleeve_id ?? '',
        Number(h.quantity),
        Number(h.avg_cost),
        p, v, pnl, wt,
      ]
    })
    const holdWs = XLSX.utils.aoa_to_sheet([holdHeaders, ...holdRows])
    holdWs['!cols'] = [
      { wch: 32 }, { wch: 14 }, { wch: 10 }, { wch: 24 }, { wch: 8 },
      { wch: 14 }, { wch: 14 }, { wch: 14 },
      { wch: 18 }, { wch: 18 }, { wch: 10 },
    ]
    XLSX.utils.book_append_sheet(wb, holdWs, 'Holdings')

    // Sheet 4: Dividends (only if data loaded)
    if (dividends?.positions?.length > 0) {
      const divSummary = [
        ['Est. annual income (₦)', dividends.totalEstimatedIncome ?? 0],
        ['Conservative range (₦)', dividends.incomeForecastLow ?? 0],
        ['Optimistic range (₦)', dividends.incomeForecastHigh ?? 0],
        ['Portfolio yield', dividends.portfolioYield ?? 0],
        ['Income target', dividends.incomeTarget ?? 0],
        ['Income gap (₦)', dividends.incomeTargetGap ?? 0],
        ['Paying positions', dividends.payingPositions ?? 0],
        ['Suspended positions', dividends.suspendedPositions ?? 0],
        [''],
      ]
      const divHeaders = ['Stock', 'Ticker', 'Shares', 'DPS (₦)', 'Yield %', 'Annual Income (₦)', 'Status', 'Last Dividend']
      const divRows = dividends.positions.map((p: any) => [
        p.name, p.instrumentId,
        p.shares ?? 0,
        p.divPerShare > 0 ? p.divPerShare : '',
        p.divYieldPct > 0 ? Number((p.divYieldPct * 100).toFixed(2)) : '',
        p.annualIncome > 0 ? p.annualIncome : '',
        p.divStatus ?? '',
        p.lastDivDate ?? p.nextDivDate ?? '',
      ])
      const divWs = XLSX.utils.aoa_to_sheet([...divSummary, divHeaders, ...divRows])
      divWs['!cols'] = [
        { wch: 28 }, { wch: 14 }, { wch: 12 },
        { wch: 10 }, { wch: 10 }, { wch: 18 }, { wch: 12 }, { wch: 14 },
      ]
      XLSX.utils.book_append_sheet(wb, divWs, 'Dividends')
    }

    const fileDate = new Date().toISOString().slice(0, 10)
    XLSX.writeFile(wb, `${clientName} - ${portfolioName} Overview ${fileDate}.xlsx`)
  }

  return (
    <main className="hybrid-page" style={{ padding: '32px 44px 64px', minHeight: '100vh' }}>
      <div className="page-head">
        <div>
          <div className="eyebrow" style={{ marginBottom: 10 }}>
            {(portfolio as any).client?.name}
          </div>
          <h1 className="hybrid-serif" style={{ fontSize: 36, fontWeight: 500, letterSpacing: '-0.005em', lineHeight: 1, color: 'var(--text)' }}>
            {portfolio.name}
          </h1>
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          <span className="btn-h" style={{ pointerEvents: 'none', opacity: 0.85 }}>
            USD/NGN ₦{Math.round(fxRate).toLocaleString()}
          </span>
          <button className="btn-h" onClick={refreshPrices} disabled={refreshing}>
            <RefreshCw size={12} className={refreshing ? 'animate-spin' : ''} />
            {refreshing ? 'Fetching…' : 'Live prices'}
          </button>
          <button className="btn-h" onClick={downloadExcel}>
            <FileSpreadsheet size={12} /> Export Excel
          </button>
          {/* v21y: Run scenario */}
          <button className="btn-h" onClick={() => setScenarioOpen(true)}>
            <Sparkles size={12} /> Run scenario
          </button>
          {/* PITFALL #7 — DO NOT REMOVE: Download report */}
          <button
            className="btn-h"
            onClick={() => window.open('/api/export?portfolioId=' + portfolioId, '_blank', 'width=1024,height=800')}
          >
            <Download size={12} /> Download report
          </button>
          <Link href={`/portfolio/${portfolioId}/reports`} className="btn-h btn-h-primary" style={{ textDecoration: 'none' }}>
            <FileText size={12} /> Generate report
          </Link>
        </div>
      </div>

      {alerts && alerts.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          {alerts.map((a: any, i: number) => (
            <div key={i} className={`alert-h ${a.level === 'critical' ? 'alert-h-critical' : 'alert-h-warn'}`}>
              <AlertTriangle size={14} style={{ marginTop: 2, flexShrink: 0 }} />
              <span>
                <strong>{a.level === 'critical' ? 'Breach: ' : 'Warning: '}</strong>
                {a.message}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* ── KPI row ────────────────────────────────────────────────────────── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginBottom: 28 }}>

        {/* KPI 1: Current NAV */}
        <div className="h-kpi">
          <div className="h-kpi-label">Current NAV</div>
          <div className={`h-kpi-value ${tot > 0 ? 'pos' : ''}`}>{fmt.ngnM(tot)}</div>
          <div className="h-kpi-sub">
            {analyticsLoading && !analytics ? (
              <span style={{ color: 'var(--text-4)' }}>Loading IRR…</span>
            ) : itdIRRDisplay.hasValue ? (
              <>
                <span className={itdIRR! >= 0 ? 'delta-pos' : 'delta-neg'}>
                  {itdIRR! >= 0 ? '▲' : '▼'} {itdIRRDisplay.value} p.a.
                </span>
                {' '}IRR (ITD)
              </>
            ) : hasStartingNav ? (
              <span style={{ color: 'var(--text-3)', fontSize: 10 }}>
                vs ₦{fmt.ngnM(portfolio.starting_nav)} starting
              </span>
            ) : (
              'Built from transactions'
            )}
          </div>
        </div>

        {/* KPI 2: Starting NAV — unchanged */}
        <div className="h-kpi">
          <div className="h-kpi-label">Starting NAV</div>
          <div className="h-kpi-value">{hasStartingNav ? fmt.ngnM(portfolio.starting_nav) : '—'}</div>
          <div className="h-kpi-sub">Inception {fmt.date(portfolio.start_date)}</div>
        </div>

        {/* KPI 3: Unrealised P&L */}
        <div className="h-kpi">
          <div className="h-kpi-label">Unrealised P&amp;L</div>
          <div className={`h-kpi-value ${pl >= 0 ? 'pos' : 'neg'}`}>
            {pl >= 0 ? '+' : ''}{fmt.ngnM(pl)}
          </div>
          <div className="h-kpi-sub">
            {analyticsLoading && !analytics ? (
              <span style={{ color: 'var(--text-4)' }}>Loading IRR…</span>
            ) : itdIRRDisplay.hasValue ? (
              <span className={itdIRR! >= 0 ? 'delta-pos' : 'delta-neg'}>
                {itdIRRDisplay.value} p.a. IRR
              </span>
            ) : hasStartingNav ? (
              <span style={{ color: 'var(--text-3)', fontSize: 10 }}>
                net gain over starting capital
              </span>
            ) : (
              'No reference basis'
            )}
          </div>
        </div>

        {/* KPI 4: Est. Income — unchanged */}
        <div className="h-kpi">
          <div className="h-kpi-label">Est. Income p.a.</div>
          <div className="h-kpi-value accent">{fmt.ngnM(incPA || 0)}</div>
          <div className="h-kpi-sub">
            Target {((portfolio.income_target ?? 0) * 100).toFixed(0)}%
            {incPA && portfolio.income_target && tot > 0 ? (
              incPA / tot >= portfolio.income_target ? ' · on target' : ' · shortfall'
            ) : ''}
          </div>
        </div>
      </div>

      {/* Performance panel (v21g) — unchanged, was always correct */}
      <div className="panel" style={{ marginBottom: 20 }}>
        <div className="panel-header">
          <div>
            <div className="panel-title">Performance</div>
            <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 2 }}>
              {metrics
                ? `${metrics.startDate} → ${metrics.endDate} · ${daysHeld ?? 0} days held`
                : 'Loading period metrics…'}
            </div>
          </div>
          <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap', justifyContent: 'flex-end' }}>
            {/* v27j: each tab gates on allPeriods[t.key].available; unavailable tabs greyed with tooltip */}
            {PERIOD_TABS.map(t => {
              const active = t.key === analyticsPeriod
              const periodMeta: any = analytics?.allPeriods?.find((p: any) => p.period === t.key)
              const isAvailable: boolean = periodMeta ? periodMeta.available !== false : true
              const reason: string | undefined = periodMeta?.unavailableReason
              const dynamicLabel: string | undefined = periodMeta?.dynamicLabel
              const tabLabel = dynamicLabel ?? t.label
              const isDisabled = analyticsLoading || !isAvailable
              return (
                <button
                  key={t.key}
                  onClick={() => { if (isAvailable) setAnalyticsPeriod(t.key) }}
                  disabled={isDisabled}
                  title={!isAvailable ? reason : undefined}
                  style={{
                    padding: '5px 10px', fontSize: 11, fontWeight: 600,
                    letterSpacing: '0.04em', fontFamily: 'var(--font-sans)',
                    border: `1px solid ${active ? 'var(--gold)' : 'var(--border-strong)'}`,
                    background: active ? 'var(--gold-soft)' : 'transparent',
                    color: !isAvailable ? 'var(--text-3)' : (active ? 'var(--gold)' : 'var(--text-2)'),
                    opacity: !isAvailable ? 0.45 : 1,
                    borderRadius: 3,
                    cursor: analyticsLoading ? 'wait' : (!isAvailable ? 'not-allowed' : 'pointer'),
                    transition: 'all 0.15s',
                  }}
                >
                  {tabLabel}
                </button>
              )
            })}
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1.3fr 1fr 1fr 1fr', gap: 24, paddingBottom: 20, borderBottom: '1px solid var(--border-soft)', marginBottom: 18 }}>
          <div>
            <div style={{ fontSize: 10, letterSpacing: '0.16em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 10 }}>
              IRR ({periodLabel})
            </div>
            <div
              className="hybrid-serif"
              style={{
                fontSize: 44, fontWeight: 500, letterSpacing: '-0.015em', lineHeight: 1,
                color: irrDisplay.hasValue ? (metrics?.irr >= 0 ? 'var(--pos)' : 'var(--neg)') : 'var(--text-3)',
                marginBottom: 8,
              }}
            >
              {irrDisplay.value}
              {irrDisplay.hasValue && (
                <span style={{ fontSize: 18, color: 'var(--text-2)', fontWeight: 400, marginLeft: 6, letterSpacing: '0.01em' }}>p.a.</span>
              )}
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-2)', lineHeight: 1.4 }}>
              {irrDisplay.hasValue ? 'Money-weighted return, annualised' :
                !hasEnoughDataForIRR ? <span style={{ color: 'var(--warn)' }}>Need starting NAV &gt; 0 and ≥1 day held</span> :
                'Insufficient cashflow data for this period'}
            </div>
            {irrDisplay.hasValue && (
              <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 4, fontStyle: 'italic' }}>
                Excludes dividends paid to client bank account
              </div>
            )}
          </div>
          <div>
            <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 10 }}>Period return</div>
            <div className="hybrid-serif" style={{ fontSize: 22, fontWeight: 500, letterSpacing: '-0.01em', color: metrics?.simplePeriodReturn !== null && metrics?.simplePeriodReturn !== undefined ? (metrics.simplePeriodReturn >= 0 ? 'var(--pos)' : 'var(--neg)') : 'var(--text-3)', marginBottom: 4 }}>
              {fmtPctSigned(metrics?.simplePeriodReturn)}
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-2)' }}>Un-annualised</div>
          </div>
          <div>
            <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 10 }}>Absolute P&amp;L</div>
            <div className="hybrid-serif" style={{ fontSize: 22, fontWeight: 500, letterSpacing: '-0.01em', color: metrics?.absoluteReturn !== null && metrics?.absoluteReturn !== undefined ? (metrics.absoluteReturn >= 0 ? 'var(--pos)' : 'var(--neg)') : 'var(--text-3)', marginBottom: 4 }}>
              {metrics?.absoluteReturn !== null && metrics?.absoluteReturn !== undefined
                ? `${metrics.absoluteReturn >= 0 ? '+' : '−'}${fmt.ngnM(Math.abs(metrics.absoluteReturn))}`
                : '—'}
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-2)' }}>Net of external flows</div>
          </div>
          <div>
            <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 10 }}>
              TWR {metrics?.twrAnnualised !== null && metrics?.twrAnnualised !== undefined ? '(ann.)' : ''}
            </div>
            <div className="hybrid-serif" style={{ fontSize: 22, fontWeight: 500, letterSpacing: '-0.01em', color: metrics?.twr !== null && metrics?.twr !== undefined && metrics.twr !== 0 ? (metrics.twr >= 0 ? 'var(--pos)' : 'var(--neg)') : 'var(--text-3)', marginBottom: 4 }}>
              {metrics?.twrAnnualised !== null && metrics?.twrAnnualised !== undefined ? fmtPctSigned(metrics.twrAnnualised) : fmtPctSigned(metrics?.twr)}
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-2)' }}>
              Time-weighted{daysHeld !== null && daysHeld <= 365 && metrics?.twr !== null ? ' · period return' : ''}
            </div>
          </div>
        </div>

        <div>
          <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 12, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <span>Benchmarks ({periodLabel}, annual rate)</span>
            {daysHeld !== null && daysHeld < 365 && (
              <span style={{ fontSize: 9, color: 'var(--text-3)', fontWeight: 400, letterSpacing: 0, textTransform: 'none', fontStyle: 'italic' }}>
                Sub-year periods show annual equivalent for fair comparison
              </span>
            )}
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 12 }}>
            {(metrics?.benchmarks ?? []).map((b: any) => (
              <div key={b.shortName} style={{ padding: '10px 12px', background: 'var(--bg-soft)', border: '1px solid var(--border-soft)', borderRadius: 4 }}>
                <div style={{ fontSize: 10, color: 'var(--text-3)', letterSpacing: '0.06em', fontWeight: 600, marginBottom: 4 }}>{b.shortName}</div>
                <div className="hybrid-serif" style={{ fontSize: 16, fontWeight: 500, letterSpacing: '-0.005em', color: b.annualRate >= 0 ? 'var(--pos)' : 'var(--neg)' }}>
                  {fmtPctSigned(b.annualRate, 1)}
                </div>
              </div>
            ))}
            {(!metrics?.benchmarks || metrics.benchmarks.length === 0) && (
              <div style={{ gridColumn: '1 / -1', fontSize: 11, color: 'var(--text-3)' }}>Benchmarks unavailable for this period</div>
            )}
          </div>
        </div>

        {/* v27l: IRR audit panel — collapsible cash-flow detail */}
        {metrics && metrics.startNAV !== null && metrics.startNAV !== undefined && (
          <div style={{ marginTop: 16, paddingTop: 12, borderTop: '1px solid var(--border-soft)' }}>
            <button
              onClick={() => setShowAudit(s => !s)}
              style={{
                background: 'transparent', border: 'none', padding: 0,
                fontSize: 11, color: 'var(--text-2)', cursor: 'pointer',
                fontFamily: 'inherit', display: 'flex', alignItems: 'center', gap: 6,
              }}
            >
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: 9 }}>{showAudit ? '▾' : '▸'}</span>
              <span>{showAudit ? 'Hide IRR audit' : 'Show IRR audit'}</span>
            </button>
            {showAudit && (
              <div style={{ marginTop: 12, padding: '12px 14px', background: 'var(--bg-soft)', border: '1px solid var(--border-soft)', borderRadius: 4, fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-2)', lineHeight: 1.7 }}>
                <div style={{ fontWeight: 600, color: 'var(--text)', marginBottom: 8, fontFamily: 'var(--font-sans)', fontSize: 12 }}>
                  IRR audit — {periodLabel}
                </div>
                <div style={{ marginBottom: 6, color: 'var(--text-3)', fontFamily: 'var(--font-sans)', fontSize: 10 }}>
                  Computed against starting NAV of {fmt.ngnM(metrics.startNAV ?? 0)} on {metrics.startDate}.
                </div>
                <div style={{ marginBottom: 10, color: 'var(--text-3)', fontFamily: 'var(--font-sans)' }}>
                  Cash flows used in IRR computation:
                </div>
                <div>
                  <div style={{ display: 'grid', gridTemplateColumns: '90px 1fr 130px', gap: 8 }}>
                    <span>{metrics.startDate}</span>
                    <span>Beginning NAV</span>
                    <span style={{ textAlign: 'right', color: 'var(--neg)' }}>−{fmt.ngnM(metrics.startNAV)}</span>
                  </div>
                  {metrics.inflows > 0 && (
                    <div style={{ display: 'grid', gridTemplateColumns: '90px 1fr 130px', gap: 8 }}>
                      <span>(period)</span>
                      <span>Total TRANSFER_IN flows</span>
                      <span style={{ textAlign: 'right', color: 'var(--neg)' }}>−{fmt.ngnM(metrics.inflows)}</span>
                    </div>
                  )}
                  {metrics.outflows > 0 && (
                    <div style={{ display: 'grid', gridTemplateColumns: '90px 1fr 130px', gap: 8 }}>
                      <span>(period)</span>
                      <span>Total TRANSFER_OUT flows</span>
                      <span style={{ textAlign: 'right', color: 'var(--pos)' }}>+{fmt.ngnM(metrics.outflows)}</span>
                    </div>
                  )}
                  <div style={{ display: 'grid', gridTemplateColumns: '90px 1fr 130px', gap: 8 }}>
                    <span>{metrics.endDate}</span>
                    <span>Ending NAV</span>
                    <span style={{ textAlign: 'right', color: 'var(--pos)' }}>+{fmt.ngnM(metrics.endNAV)}</span>
                  </div>
                </div>
                <div style={{ marginTop: 12, paddingTop: 10, borderTop: '1px dashed var(--border-soft)', fontFamily: 'var(--font-sans)' }}>
                  <strong style={{ color: 'var(--text)' }}>IRR (annualised): </strong>
                  <span style={{ color: irrDisplay.hasValue ? ((metrics.irr ?? 0) >= 0 ? 'var(--pos)' : 'var(--neg)') : 'var(--text-3)' }}>
                    {irrDisplay.value} {irrDisplay.hasValue ? 'p.a.' : ''}
                  </span>
                </div>
                <div style={{ marginTop: 12, color: 'var(--text-3)', fontFamily: 'var(--font-sans)', fontStyle: 'italic', fontSize: 10, lineHeight: 1.5 }}>
                  Fees (management, demat, other charges) are NOT cash-flow line items — they're already reflected in ending NAV via reduced cash holdings. IRR excludes dividends paid to client bank account, which would further improve the IRR.
                </div>
              </div>
            )}
          </div>
        )}

        {metrics && (metrics.inflows > 0 || metrics.outflows > 0) && (
          <div style={{ marginTop: 16, paddingTop: 12, borderTop: '1px solid var(--border-soft)', display: 'flex', gap: 24, fontSize: 11, color: 'var(--text-2)' }}>
            <span>Inflows: <strong style={{ color: 'var(--text)' }}>{fmt.ngnM(metrics.inflows)}</strong></span>
            <span>Outflows: <strong style={{ color: 'var(--text)' }}>{fmt.ngnM(metrics.outflows)}</strong></span>
            <span>Net: <strong style={{ color: metrics.netCashFlows >= 0 ? 'var(--pos)' : 'var(--neg)' }}>{metrics.netCashFlows >= 0 ? '+' : '−'}{fmt.ngnM(Math.abs(metrics.netCashFlows))}</strong></span>
          </div>
        )}
      </div>

      {/* v27l: Performance fee calculation panel */}
      {analytics?.feeMetrics && (
        <div className="panel" style={{ marginBottom: 20 }}>
          <div className="panel-header">
            <div>
              <div className="panel-title">Performance fee calculation ({periodLabel})</div>
              <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 2 }}>
                Threshold: {((analytics?.targetReturn ?? 0.15) * 100).toFixed(1)}% p.a.
                {' · '}
                {analytics.feeMetrics.belowTarget
                  ? <span style={{ color: 'var(--text-3)' }}>Below target — no fee earned this period</span>
                  : <span style={{ color: 'var(--pos)' }}>Excess return: +{fmt.ngnM(analytics.feeMetrics.excessReturn)}</span>}
              </div>
            </div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, paddingBottom: 16, borderBottom: '1px solid var(--border-soft)', marginBottom: 16 }}>
            <div>
              <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 6 }}>Contributed capital</div>
              <div className="hybrid-serif" style={{ fontSize: 22, fontWeight: 500, letterSpacing: '-0.01em', color: 'var(--text)', marginBottom: 4 }}>
                {fmt.ngnM(analytics.feeMetrics.contributedCapital)}
              </div>
              <div style={{ fontSize: 10, color: 'var(--text-3)' }}>Timing-adjusted</div>
            </div>
            <div>
              <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 6 }}>Target value</div>
              <div className="hybrid-serif" style={{ fontSize: 22, fontWeight: 500, letterSpacing: '-0.01em', color: 'var(--text)', marginBottom: 4 }}>
                {fmt.ngnM(analytics.feeMetrics.targetValue)}
              </div>
              <div style={{ fontSize: 10, color: 'var(--text-3)' }}>At {((analytics?.targetReturn ?? 0.15) * 100).toFixed(0)}% p.a.</div>
            </div>
            <div>
              <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 6 }}>Actual value</div>
              <div className="hybrid-serif" style={{ fontSize: 22, fontWeight: 500, letterSpacing: '-0.01em', color: 'var(--text)', marginBottom: 4 }}>
                {fmt.ngnM(analytics.feeMetrics.actualValue)}
              </div>
              <div style={{ fontSize: 10, color: 'var(--text-3)' }}>Ending NAV</div>
            </div>
            <div>
              <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 6 }}>Excess return</div>
              <div
                className="hybrid-serif"
                style={{
                  fontSize: 22, fontWeight: 500, letterSpacing: '-0.01em',
                  color: analytics.feeMetrics.belowTarget ? 'var(--neg)' : 'var(--pos)',
                  marginBottom: 4,
                }}
              >
                {analytics.feeMetrics.belowTarget ? '−' : '+'}{fmt.ngnM(Math.abs(analytics.feeMetrics.excessReturn))}
              </div>
              <div style={{ fontSize: 10, color: 'var(--text-3)' }}>Actual − Target</div>
            </div>
          </div>
          {!analytics.feeMetrics.belowTarget && (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16, marginBottom: 12 }}>
              <div>
                <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 6 }}>Client share (70%)</div>
                <div className="hybrid-serif" style={{ fontSize: 18, fontWeight: 500, letterSpacing: '-0.005em', color: 'var(--pos)' }}>
                  +{fmt.ngnM(analytics.feeMetrics.clientFee)}
                </div>
              </div>
              <div>
                <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 6 }}>Transworld share (30%)</div>
                <div className="hybrid-serif" style={{ fontSize: 18, fontWeight: 500, letterSpacing: '-0.005em', color: 'var(--gold)' }}>
                  {fmt.ngnM(analytics.feeMetrics.transworldFee)}
                </div>
              </div>
              <div>
                <div style={{ fontSize: 10, letterSpacing: '0.14em', fontWeight: 600, color: 'var(--text-3)', textTransform: 'uppercase', marginBottom: 6 }}>Effective return</div>
                <div className="hybrid-serif" style={{ fontSize: 18, fontWeight: 500, letterSpacing: '-0.005em', color: 'var(--pos)' }}>
                  +{(analytics.feeMetrics.effectiveReturnPct * 100).toFixed(1)}%
                </div>
                <div style={{ fontSize: 10, color: 'var(--text-3)' }}>Net of fee</div>
              </div>
            </div>
          )}
          <div style={{ marginTop: 12, padding: '10px 12px', background: 'var(--bg-soft)', border: '1px solid var(--border-soft)', borderRadius: 4, fontSize: 10, color: 'var(--text-2)', lineHeight: 1.6 }}>
            <strong style={{ color: 'var(--text)' }}>Method:</strong>{' '}
            Timing-adjusted contributed capital uses standard portfolio-finance interpretation
            (each cash flow contributes amount × years remaining in period). Target value compounds at threshold rate.
            {' '}<em>Excludes dividends paid to client bank account, which would further improve effective return.</em>
            {' '}Threshold editable on Portfolio settings.
          </div>
        </div>
      )}

      {/* Allocation bars + Composition donut */}
      <div style={{ display: 'grid', gridTemplateColumns: '1.5fr 1fr', gap: 14, marginBottom: 20 }}>
        <div className="panel">
          <div className="panel-header">
            <div className="panel-title">Allocation vs. Targets</div>
            <div className="panel-meta">{sv.length} Sleeves</div>
          </div>
          {sv.map((s: any) => {
            const act    = (s.act ?? 0) * 100
            const target = (s.target_pct ?? 0) * 100
            const min    = (s.min_pct ?? 0) * 100
            const max    = (s.max_pct ?? 1) * 100
            const status = s.status === 'OK' || s.status === 'ok' ? 'ok' : s.status === 'BREACH' || s.status === 'breach' ? 'breach' : 'warn'
            const pillClass = status === 'ok' ? 'pill pill-ok' : status === 'breach' ? 'pill pill-breach' : 'pill pill-warn'
            const fill   = SLEEVE_FILL[s.sleeve_id] ?? 'var(--text-4)'
            return (
              <div key={s.sleeve_id} className="sleeve-bar-row">
                <div className="sleeve-bar-head">
                  <div className="sleeve-bar-label">{s.name}</div>
                  <div>
                    <span className="sleeve-bar-actual">{act.toFixed(1)}<span className="unit">%</span></span>
                    &nbsp;&nbsp;
                    <span className={pillClass}>{s.status ?? 'OK'}</span>
                  </div>
                </div>
                <div className="sleeve-bar-track">
                  <div className="sleeve-bar-fill" style={{ width: `${Math.min(100, act)}%`, background: fill }} />
                </div>
                <div className="sleeve-bar-sub">
                  <span>Range {min.toFixed(1)}% – {max.toFixed(1)}%</span>
                  <span>Target {target.toFixed(1)}% · {fmt.ngnM(tot * (s.target_pct ?? 0))}</span>
                </div>
              </div>
            )
          })}
        </div>
        <div className="panel">
          <div className="panel-header"><div className="panel-title">Composition</div></div>
          <AllocationDonut sleeves={sv as any} totalNAV={tot} />
        </div>
      </div>

      {/* v21h: Sector Concentration */}
      {sectorSlices.length > 0 && (
        <div className="panel" style={{ marginBottom: 20 }}>
          <div className="panel-header">
            <div>
              <div className="panel-title">Sector Concentration</div>
              <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 2 }}>
                NAV-weighted breakdown of held equities by NGX sector
              </div>
            </div>
            <div className="panel-meta">{sectorSlices.length} sector{sectorSlices.length === 1 ? '' : 's'}</div>
          </div>
          <SectorDonut slices={sectorSlices} totalEquityNAV={totalEquityNAV} />
        </div>
      )}

      {/* Rebalancing */}
      <div className="panel" style={{ marginBottom: 20 }}>
        <div className="panel-header">
          <div className="panel-title">Rebalancing Guide</div>
          <div className="panel-meta">Based on targets · {fmt.date((portfolio as any).valuation_date ?? portfolio.start_date)}</div>
        </div>
        <table className="h-table">
          <thead>
            <tr>
              <th>Sleeve</th>
              <th className="num">Target value</th>
              <th className="num">Actual value</th>
              <th className="num">Deviation</th>
              <th>Status</th>
              <th>Suggested</th>
            </tr>
          </thead>
          <tbody>
            {sv.map((s: any) => {
              const d          = s.diff ?? 0
              const action     = d > 50000 ? 'Buy' : d < -50000 ? 'Sell' : 'Hold'
              const actionPill = action === 'Buy' ? 'pill pill-buy' : action === 'Sell' ? 'pill pill-sell' : 'pill pill-hold'
              const statusPill = s.status === 'OK' ? 'pill pill-ok' : s.status === 'BREACH' ? 'pill pill-breach' : 'pill pill-warn'
              const sleeveColor = s.sleeve_id === 'liq' ? 'var(--sidebar-bg)' : s.sleeve_id === 'eq' ? 'var(--gold)' : 'var(--pos)'
              return (
                <tr key={s.sleeve_id}>
                  <td><span style={{ color: sleeveColor, marginRight: 6 }}>●</span>{s.name}</td>
                  <td className="num num-serif">{fmt.ngnM(tot * (s.target_pct ?? 0))}</td>
                  <td className="num num-serif">{fmt.ngnM(s.val ?? 0)}</td>
                  <td className="num num-serif" style={{ color: d >= 0 ? 'var(--pos)' : 'var(--neg)' }}>
                    {d >= 0 ? '+' : '−'}{fmt.ngnM(Math.abs(d))}
                  </td>
                  <td><span className={statusPill}>{s.status}</span></td>
                  <td><span className={actionPill}>{action}</span></td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* Dividend Income Panel */}
      {divLoading && !dividends ? (
        <div className="panel">
          <div className="panel-header"><div className="panel-title">Estimated Dividend Income</div></div>
          <div style={{ padding: '24px 0', textAlign: 'center', color: 'var(--text-3)', fontSize: 12 }}>Loading dividend data…</div>
        </div>
      ) : dividends ? (
        <div className="panel">
          <div className="panel-header">
            <div>
              <div className="panel-title">Estimated Dividend Income</div>
              <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 2 }}>Last declared DPS × current shares held</div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
              <span className="staleness-caption">
                <span className={`staleness-dot ${divStaleInfo.cls}`} />
                {divStaleInfo.text}
              </span>
              {divRefreshMsg && (
                <span style={{ fontSize: 10, color: divRefreshMsg.startsWith('✓') ? 'var(--pos)' : 'var(--neg)' }}>{divRefreshMsg}</span>
              )}
              <button className="btn-h" onClick={refreshDividends} disabled={divRefreshing}>
                <RefreshCw size={11} className={divRefreshing ? 'animate-spin' : ''} />
                {divRefreshing ? 'Refreshing…' : 'Refresh from NGX'}
              </button>
            </div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 20 }}>
            <div className="div-kpi">
              <div className="div-kpi-label">Est. Annual Income</div>
              <div className="div-kpi-value">₦{((dividends.totalEstimatedIncome ?? 0) / 1e6).toFixed(2)}M</div>
              <div style={{ fontSize: 10, color: 'var(--text-2)', marginTop: 4 }}>{((dividends.portfolioYield ?? 0) * 100).toFixed(2)}% portfolio yield</div>
            </div>
            <div className="div-kpi">
              <div className="div-kpi-label">Conservative range</div>
              <div className="div-kpi-value">₦{((dividends.incomeForecastLow ?? 0) / 1e6).toFixed(2)}M</div>
              <div style={{ fontSize: 10, color: 'var(--text-2)', marginTop: 4 }}>Declared + confirmed only</div>
            </div>
            <div className="div-kpi">
              <div className="div-kpi-label">Optimistic range</div>
              <div className="div-kpi-value">₦{((dividends.incomeForecastHigh ?? 0) / 1e6).toFixed(2)}M</div>
              <div style={{ fontSize: 10, color: 'var(--text-2)', marginTop: 4 }}>Incl. potential resumptions</div>
            </div>
            <div className="div-kpi">
              <div className="div-kpi-label">Income target ({((dividends.incomeTarget ?? 0) * 100).toFixed(0)}%)</div>
              <div className="div-kpi-value" style={{ color: (dividends.incomeTargetGap ?? 0) > 0 ? 'var(--neg)' : 'var(--pos)' }}>
                {(dividends.incomeTargetGap ?? 0) > 0
                  ? `₦${(dividends.incomeTargetGap / 1e6).toFixed(2)}M short`
                  : `₦${(Math.abs(dividends.incomeTargetGap ?? 0) / 1e6).toFixed(2)}M above`}
              </div>
              <div style={{ fontSize: 10, color: 'var(--text-2)', marginTop: 4 }}>{dividends.payingPositions ?? 0} paying · {dividends.suspendedPositions ?? 0} suspended</div>
            </div>
          </div>
          <table className="h-table">
            <thead>
              <tr>
                <th>Stock</th>
                <th className="num">Shares</th>
                <th className="num">DPS</th>
                <th className="num">Yield</th>
                <th className="num">Annual Income</th>
                <th>Status</th>
                <th>Last Div</th>
              </tr>
            </thead>
            <tbody>
              {(dividends.positions ?? []).map((p: any) => {
                const statusPill = p.divStatus === 'paying' ? 'pill pill-ok' : p.divStatus === 'suspended' ? 'pill pill-breach' : 'pill pill-hold'
                return (
                  <tr key={p.instrumentId}>
                    <td>
                      <div style={{ fontWeight: 500 }}>{p.name}</div>
                      <div style={{ fontSize: 10, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>{p.instrumentId}</div>
                    </td>
                    <td className="num" style={{ fontFamily: 'var(--font-mono)' }}>{(p.shares ?? 0).toLocaleString()}</td>
                    <td className="num num-serif">{p.divPerShare > 0 ? `₦${p.divPerShare.toFixed(2)}` : '—'}</td>
                    <td className="num" style={{ fontFamily: 'var(--font-mono)' }}>{p.divYieldPct > 0 ? `${(p.divYieldPct * 100).toFixed(2)}%` : '—'}</td>
                    <td className="num num-serif" style={{ color: p.annualIncome > 0 ? 'var(--pos)' : 'var(--text-3)' }}>
                      {p.annualIncome > 0 ? `₦${p.annualIncome.toLocaleString('en-NG', { maximumFractionDigits: 0 })}` : '—'}
                    </td>
                    <td><span className={statusPill}>{p.divStatus ?? 'unknown'}</span></td>
                    <td style={{ fontSize: 11, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>{p.lastDivDate ?? p.nextDivDate ?? '—'}</td>
                  </tr>
                )
              })}
            </tbody>
          </table>
          {dividends.methodology && (
            <div style={{ marginTop: 14, padding: '10px 12px', background: 'var(--bg-soft)', border: '1px solid var(--border-soft)', borderRadius: 4, fontSize: 10, color: 'var(--text-2)', lineHeight: 1.6, display: 'flex', alignItems: 'flex-start', gap: 6 }}>
              <Info size={11} style={{ marginTop: 2, flexShrink: 0, color: 'var(--gold)' }} />
              <span><strong style={{ color: 'var(--text)' }}>Methodology:</strong> {dividends.methodology}</span>
            </div>
          )}
        </div>
      ) : null}

      {/* v21y: Scenario analysis modal */}
      {scenarioOpen && (
        <ScenarioModal
          portfolioId={portfolioId}
          portfolioName={portfolio.name}
          clientName={(portfolio as any).client?.name ?? ''}
          onClose={() => setScenarioOpen(false)}
        />
      )}
    </main>
  )
}
